### ISSUE TITLE
Suggestion: [CoolerEclipseLobby Compatibility]

### ISSUE THREAD

**Issue by Expakun** [DestroyedClone/LobbyAppearanceImprovements#10]
I would really like to be able to choose the CoolerEclipseLobby Scene as my Scene in LobbyAppearanceImprovements.

**Comment by DestroyedClone** [comment]
Added with https://github.com/DestroyedClone/LobbyAppearanceImprovements/commit/b35782bc49c198453180c7b2bc6155a8c48637b8

Closing issue when next update is released.
